-- Expand CMS keys for editable site content (marquee, events, intros)

insert into public.site_content (key, label, value) values
  ('home_intro', 'Home hero intro', '{"badge":"Transforming Education for Viksit Bharat","title_line1":"Department of","title_line2":"Holistic Education","description":"The Department of Holistic Education (DHE) is a national educational transformation platform dedicated to building Bharat as a global knowledge leader through value-based education, innovation, research, entrepreneurship, and holistic human development aligned with NEP 2020."}'::jsonb),
  ('footer_mission', 'Footer mission blurb', '{"text":"DHE integrates educational leadership, innovation, skill development, research, entrepreneurship, publications, digital transformation, and institutional collaboration into one unified ecosystem empowering Bharat towards becoming a global knowledge leader."}'::jsonb),
  ('donation_intro', 'Donation page intro', '{"text":"Your contribution helps advance holistic education, national programs, and institutional initiatives led by DHE in service of educational transformation and Viksit Bharat."}'::jsonb),
  ('programs_intro', 'Programs page intro', '{"text":"Flagship programs and cells advancing holistic education across Bharat."}'::jsonb),
  ('marquee_items', 'News marquee', '{"json":"[{\"text\":\"Shiksha Mahakumbh 6.0 — NIT Hamirpur, 9–11 Oct 2026. Registration open.\",\"link\":\"https://www.rase.co.in/registration/Single_Registration\"},{\"text\":\"Shiksha Mahakumbh 5.0 concluded at NIPER Mohali. View photos.\",\"link\":\"https://drive.google.com/drive/folders/1c2CKx2Z9IaN-dsoW-Ymw6Npx1EOTFcsA\"},{\"text\":\"Join the holistic education movement — explore DHE programs.\",\"link\":\"/programs\"}]"}'::jsonb),
  ('upcoming_events', 'Upcoming events', '{"json":"[{\"title\":\"Shiksha Mahakumbh 6.0\",\"date\":\"9–11 October 2026\",\"venue\":\"NIT Hamirpur, Himachal Pradesh\",\"href\":\"https://www.rase.co.in/registration/Single_Registration\",\"external\":true,\"status\":\"planned\",\"statusLabel\":\"Registration Open\"},{\"title\":\"Shiksha Mahakumbh 5.0\",\"date\":\"31 October – 2 November 2025\",\"venue\":\"NIPER Mohali\",\"href\":\"https://drive.google.com/drive/folders/1c2CKx2Z9IaN-dsoW-Ymw6Npx1EOTFcsA\",\"external\":true,\"status\":\"completed\",\"statusLabel\":\"Concluded\"},{\"title\":\"Indian Education System for Global Development\",\"date\":\"December 16–17, 2024\",\"venue\":\"Kurukshetra University\",\"href\":\"https://www.shikshamahakumbh.com/\",\"external\":true,\"status\":\"completed\",\"statusLabel\":\"Archived\"}]"}'::jsonb)
on conflict (key) do nothing;

-- Extend director_message with full body if missing
update public.site_content
set value = value || '{"body":"The Department of Holistic Education (DHE) is a national educational transformation platform dedicated to building Bharat as a global knowledge leader through value-based education, innovation, research, entrepreneurship, and holistic human development aligned with NEP 2020.\n\nInspired by the transformative educational philosophy of Vidya Bharati, DHE advances holistic education, skill development, leadership, and Bharatiya values through programs, cells, and national initiatives such as Shiksha Mahakumbh."}'::jsonb
where key = 'director_message' and not (value ? 'body');
